### ISSUE TITLE
建议：表意更清晰的component名称

### ISSUE THREAD

**Issue by ttimasdf** [serverless-components/tencent-flask#3]
TL,DR 建议改名成 tencent-wsgi

现在官方文档中，腾讯云Serverless Framework对于Python的支持只提到了能部署Flask框架。但实际上，任何支持WSGI的Python服务端框架都可以通过这一套shim来转发到API网关，这个差距很大的好不好……要不是提了个工单问了一下，我已经被文档劝退了……

测试通过的一个例子，用Falcon Framework，也兼容WSGI。部署过程就是在requirements.txt里写一行 `falcon==2.0.0`，下面的文件存成app.py，然后按文档部署即可。

```python
# app.py
import falcon

class QuoteResource:

    def on_get(self, req, resp):
        """Handles GET requests"""
        quote = {
            'quote': (
                "I've always been more interested in "
                "the future than in the past."
            ),
            'author': 'Grace Hopper'
        }

        resp.media = quote


def orphan(req: falcon.Request, resp: falcon.Response):
    resp.media = {
        "errno": "WTF",
        "msg": "What the fuck is this 404 Page?"
    }
    resp.status = falcon.HTTP_NOT_FOUND


app = falcon.API()
app.add_route('/quote', QuoteResource())
app.add_sink(orphan)
```

其实这一套东西大大降低了编写SCF的门槛。但文档写的不是很容易上手，component的名字误导性也太强。所以建议至少改个名字，告诉大家这玩意很好用……是吧

ref:
- [Serverless Framework 部署 Python Flask 框架 - 最佳实践 - 文档中心 - 腾讯云](https://cloud.tencent.com/document/product/1154/40495)
- [Serverless Framework Components 概述 - 操作指南 - 文档中心 - 腾讯云](https://cloud.tencent.com/document/product/1154/39270)

**Comment by yugasun** [comment]
@ttimasdf 感谢反馈，确实如你所说 `任何支持WSGI的Python服务端框架都可以通过这一套shim来转发到API网关`，关于更名，影响太多，需要慎重考虑。
@tinafangkunding 辛苦关注下~

**Comment by tinafangkunding** [comment]
@ttimasdf 感谢反馈和建议，我们评估了一下更名的影响确实比较大。短期会优先在文档的说明中，着重强调：支持所有 WSGI 的Python框架 。

关于 components 的名字，对应海外的产品名字 serverless components 确实不太好翻译和理解。这里还在继续讨论怎样可以更直观的让用户感知到其易用性。
